name: Update winget package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  wingetcreate-update:
    runs-on: windows-latest
    steps:
      - name: Run wingetcreate
        shell: pwsh
        run: . { iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe } | iex; wingetcreate.exe update -s -i jely2002.youtube-dl-gui -u https://github.com/jely2002/youtube-dl-gui/releases/download/v${{ github.event.inputs.version }}/YouTube-Downloader-GUI-Setup-${{ github.event.inputs.version }}.exe -v ${{ github.event.inputs.version }}  -t ${{ secrets.GITHUB_TOKEN }}
